--- #YAML:1.0
name:                   App-Maisha
version:                0.11
abstract:               A command line social micro-blog networking tool.
author:
  - Barbie <barbie@cpan.org>

license:                perl
distribution_type:      module
installdirs:            site

requires:
  Class::Accessor::Fast:    0
  Config::Any:              0
  File::HomeDir:            0
  FindBin:                  0
  Getopt::Long:             0
  Module::Pluggable:        2.7
  Net::Identica:            2.05
  Net::Twitter:             2.06
  Pod::Usage:               0
  Term::Shell:              0
  Test::More:               0.47
  Text::Wrap:               0
recommends:
  Test::CPAN::Meta:         0.12
  Test::Distribution:       2.00
  Test::More:               0.47
  Test::Pod:                1.00
  Test::Pod::Coverage:      0.08
build_requires:
  Test::More:               0.47

provides:
  App::Maisha:
    file: lib/App/Maisha.pm
    version: 0.11
  App::Maisha::Shell:
    file: lib/App/Maisha/Shell.pm
    version: 0.11
  App::Maisha::Plugin::Base:
    file: lib/App/Maisha/Plugin/Base.pm
    version: 0.11
  App::Maisha::Plugin::Identica:
    file: lib/App/Maisha/Plugin/Identica.pm
    version: 0.11
  App::Maisha::Plugin::Twitter:
    file: lib/App/Maisha/Plugin/Twitter.pm
    version: 0.11
no_index:
  directory:
    - t
    - examples

meta-spec:
   version: 1.4
   url: http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
